### ISSUE TITLE
Testing AAPL Alpaca w/StochMacd gives errors; TSLA works

### ISSUE THREAD

**Issue by solarfrantz** [debut-js/Core#16]
```
> tester -- "--ticker=AAPL" "--bot=StochMacd" "--days=20"

TypeError: Cannot read property 'broker' of undefined
    at test (Strategies\node_modules\@debut\community-core\lib\cli\tester.js:37:84)
    at Strategies\node_modules\@debut\community-core\lib\cli\tester.js:33:11
    at Object.<anonymous> (Strategies\node_modules\@debut\community-core\lib\cli\tester.js:34:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

Process finished with exit code 0
```

For some funny reason, using `--ticker=TSLA` works.

**Comment by BusinessDuck** [comment]
looks like you dont have TLSA in stochmacd `cfgs.ts` file, please read the documentation about it.
